language: node_js
sudo: required
dist: trusty
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - npm install -g bower eslint polylint polymer-cli web-component-tester yarn
  - yarn
  - eslint
  - polylint
script:
  - xvfb-run polymer test
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --email ${FIREBASE_USERNAME} --password ${FIREBASE_PASSWORD}
